/* eslint-disable */
/*Proudly generated by GenDocu.com*/
// package: winecellar
// file: example/winecellar/winecellar.proto

var example_winecellar_winecellar_pb = require("../../example/winecellar/winecellar_pb");
var grpc = require("@improbable-eng/grpc-web").grpc;

var WinecellarService = (function () {
  function WinecellarService() {}
  WinecellarService.serviceName = "winecellar.WinecellarService";
  return WinecellarService;
}());

WinecellarService.ListAll = {
  methodName: "ListAll",
  service: WinecellarService,
  requestStream: false,
  responseStream: true,
  requestType: example_winecellar_winecellar_pb.ListAllWinecellarRequest,
  responseType: example_winecellar_winecellar_pb.Winecellar
};

WinecellarService.LoadStock = {
  methodName: "LoadStock",
  service: WinecellarService,
  requestStream: false,
  responseStream: false,
  requestType: example_winecellar_winecellar_pb.LoadWinecellarStockRequest,
  responseType: example_winecellar_winecellar_pb.WinecellarStock
};

exports.WinecellarService = WinecellarService;

function WinecellarServiceClient(serviceHost, options) {
  this.serviceHost = serviceHost;
  this.options = options || {};
}

WinecellarServiceClient.prototype.listAll = function listAll(requestMessage, metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.invoke(WinecellarService.ListAll, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onMessage: function (responseMessage) {
      listeners.data.forEach(function (handler) {
        handler(responseMessage);
      });
    },
    onEnd: function (status, statusMessage, trailers) {
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
    }
  });
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

WinecellarServiceClient.prototype.loadStock = function loadStock(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(WinecellarService.LoadStock, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

exports.WinecellarServiceClient = WinecellarServiceClient;

