/* eslint-disable */
/*Proudly generated by GenDocu.com*/
// package: winecellar
// file: example/winecellar/winecellar.proto

import * as example_winecellar_winecellar_pb from "../../example/winecellar/winecellar_pb";
import {grpc} from "@improbable-eng/grpc-web";

type WinecellarServiceListAll = {
  readonly methodName: string;
  readonly service: typeof WinecellarService;
  readonly requestStream: false;
  readonly responseStream: true;
  readonly requestType: typeof example_winecellar_winecellar_pb.ListAllWinecellarRequest;
  readonly responseType: typeof example_winecellar_winecellar_pb.Winecellar;
};

type WinecellarServiceLoadStock = {
  readonly methodName: string;
  readonly service: typeof WinecellarService;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof example_winecellar_winecellar_pb.LoadWinecellarStockRequest;
  readonly responseType: typeof example_winecellar_winecellar_pb.WinecellarStock;
};

export class WinecellarService {
  static readonly serviceName: string;
  static readonly ListAll: WinecellarServiceListAll;
  static readonly LoadStock: WinecellarServiceLoadStock;
}

export type ServiceError = { message: string, code: number; metadata: grpc.Metadata }
export type Status = { details: string, code: number; metadata: grpc.Metadata }

interface UnaryResponse {
  cancel(): void;
}
interface ResponseStream<T> {
  cancel(): void;
  on(type: 'data', handler: (message: T) => void): ResponseStream<T>;
  on(type: 'end', handler: (status?: Status) => void): ResponseStream<T>;
  on(type: 'status', handler: (status: Status) => void): ResponseStream<T>;
}
interface RequestStream<T> {
  write(message: T): RequestStream<T>;
  end(): void;
  cancel(): void;
  on(type: 'end', handler: (status?: Status) => void): RequestStream<T>;
  on(type: 'status', handler: (status: Status) => void): RequestStream<T>;
}
interface BidirectionalStream<ReqT, ResT> {
  write(message: ReqT): BidirectionalStream<ReqT, ResT>;
  end(): void;
  cancel(): void;
  on(type: 'data', handler: (message: ResT) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'end', handler: (status?: Status) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'status', handler: (status: Status) => void): BidirectionalStream<ReqT, ResT>;
}

export class WinecellarServiceClient {
  readonly serviceHost: string;

  constructor(serviceHost: string, options?: grpc.RpcOptions);
  listAll(requestMessage: example_winecellar_winecellar_pb.ListAllWinecellarRequest, metadata?: grpc.Metadata): ResponseStream<example_winecellar_winecellar_pb.Winecellar>;
  loadStock(
    requestMessage: example_winecellar_winecellar_pb.LoadWinecellarStockRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: example_winecellar_winecellar_pb.WinecellarStock|null) => void
  ): UnaryResponse;
  loadStock(
    requestMessage: example_winecellar_winecellar_pb.LoadWinecellarStockRequest,
    callback: (error: ServiceError|null, responseMessage: example_winecellar_winecellar_pb.WinecellarStock|null) => void
  ): UnaryResponse;
}

