apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: sample-grpc
  name: sample-grpc
spec:
  rules:
    - host: sample-grpc.k3d.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: envoy-grpcweb-proxy
                port:
                  number: 80
  tls:
    - hosts:
        - sample-grpc.k3d.localhost
---
# exposes the service directly on node port, to bypass the ingress, which doesn't properly support http2
apiVersion: v1
kind: Service
metadata:
  name: app-winecellar-nodeport
spec:
  ports:
    - port: 80
      nodePort: 30080
      targetPort: 8080
      protocol: TCP
  selector:
    app: envoy-grpcweb-proxy
  type: NodePort
