apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: sample-grpc
  name: sample-grpc
spec:
  rules:
    - host: sample-grpcweb.k3d.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: envoy-grpcweb-proxy
                port:
                  number: 80
    - host: sample-grpcjson.k3d.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: envoy-grpcjson-proxy
                port:
                  number: 80
  tls:
    - hosts:
        - sample-grpcweb.k3d.localhost
        - sample-grpcjson.k3d.localhost
