resources:
  - resources/ingress.yaml
  - resources/envoy-proxy.yaml
  - resources/winecellar-srv.yaml
  - resources/winery-srv.yaml
configMapGenerator:
  - name: envoy-config
    files:
      - config/envoy.yaml
  - name: proto-images
    files:
      - proto/winecellar.pb
